import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONT_SIZE, FONT_WEIGHT, RADIUS } from "../constants/theme";

export const checkoutStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 60,
    position: "relative",
  },
  header: {
    height: 56,
    paddingHorizontal: SPACING.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    marginTop: -10,
  },
  backBtn: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textPrimary,
  },
  paymentRow: {
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.lg,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
  },
  paymentLabel: {
    color: COLORS.textMuted,
    fontWeight: FONT_WEIGHT.bold,
    letterSpacing: 0.3,
  },
  paymentRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  paymentMethod: {
    color: "#111827",
    fontWeight: FONT_WEIGHT.semibold,
  },
  sectionDivider: {
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
  },
  columnsHeader: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
  },
  colText: {
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textMuted,
  },
  itemRow: {
    backgroundColor: COLORS.white,
    paddingVertical: 14,
    paddingHorizontal: SPACING.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  itemLeft: {
    flex: 1,
  },
  itemTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.semibold,
    color: "#111827",
    marginBottom: SPACING.sm,
  },
  qtyControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.md,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.bold,
    marginTop: -1,
  },
  qtyValue: {
    minWidth: 24,
    textAlign: "center",
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textPrimary,
  },
  itemPrice: {
    width: 80,
    textAlign: "right",
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textPrimary,
  },
  itemSeparator: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  totalRow: {
    backgroundColor: COLORS.white,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.lg,
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
  },
  totalLabel: {
    color: COLORS.textMuted,
    fontWeight: FONT_WEIGHT.bold,
  },
  totalValue: {
    color: "#111827",
    fontWeight: FONT_WEIGHT.bold,
  },
  ctaButton: {
    marginHorizontal: SPACING.lg,
    marginBottom: 90,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    alignItems: "center",
    justifyContent: "center",
    height: 52,
  },
  ctaText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.bold,
  },
});
