import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONT_SIZE, FONT_WEIGHT, RADIUS } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 60,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: SPACING.xl,
    paddingHorizontal: SPACING.xl,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    position: "relative",
  },
  headerTitle: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    textAlign: "center",
    color: COLORS.textPrimary,
  },
  markAllButton: {
    fontSize: FONT_SIZE.md,
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.semibold,
    position: "absolute",
    right: SPACING.xl,
  },
  unreadBanner: {
    backgroundColor: "#dbeafe",
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#bfdbfe",
  },
  unreadText: {
    color: COLORS.primary,
    fontSize: FONT_SIZE.md,
    fontWeight: FONT_WEIGHT.semibold,
  },
  notificationCard: {
    backgroundColor: COLORS.white,
    paddingVertical: SPACING.xl,
    paddingHorizontal: SPACING.xl,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  unreadCard: {
    backgroundColor: "#f0f9ff",
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  notificationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SPACING.sm,
  },
  notificationTitle: {
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textSecondary,
    flex: 1,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
    marginLeft: SPACING.sm,
  },
  notificationBody: {
    fontSize: FONT_SIZE.md,
    color: COLORS.textMuted,
    marginBottom: SPACING.sm,
    lineHeight: 20,
  },
  notificationDate: {
    fontSize: FONT_SIZE.sm,
    color: COLORS.textDisabled,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  emptyText: {
    fontSize: FONT_SIZE.lg,
    color: COLORS.textDisabled,
  },
  emptyList: {
    flexGrow: 1,
  },
  unreadBadge: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.lg,
    minWidth: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SPACING.sm,
    marginLeft: SPACING.sm,
  },
  unreadBadgeText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.sm,
    fontWeight: FONT_WEIGHT.semibold,
  },
  backButtonContainer: {
    position: "absolute",
    left: SPACING.xl,
    padding: 5,
  },
  backButtonText: {
    fontSize: FONT_SIZE.title,
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.semibold,
  },
  messageRow: {
    paddingHorizontal: SPACING.xl,
    paddingVertical: SPACING.sm,
  },
  messageBubble: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    maxWidth: "85%",
  },
  messageBubbleLeft: {
    backgroundColor: COLORS.white,
    borderColor: COLORS.border,
    borderWidth: 1,
    alignSelf: "flex-start",
    marginVertical: 6,
  },
  messageBubbleRight: {
    backgroundColor: "#dbeafe",
    alignSelf: "flex-end",
    marginVertical: 6,
  },
  messageText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
  },
  inputContainer: {
    flexDirection: "row",
    padding: SPACING.md,
    borderTopWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    marginBottom: SPACING.sm,
  },
  input: {
    flex: 1,
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 10,
    fontSize: FONT_SIZE.lg,
    color: COLORS.textPrimary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  sendButton: {
    marginLeft: 10,
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: RADIUS.md,
  },
  sendButtonText: {
    color: COLORS.white,
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.semibold,
  },
  backBtn: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
});
