import { StyleSheet } from "react-native";
import { COLORS, SPACING, FONT_SIZE, FONT_WEIGHT, RADIUS, SHADOWS } from "../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 60,
  },
  header: {
    height: 56,
    paddingHorizontal: SPACING.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    marginTop: -10,
    backgroundColor: COLORS.background,
  },
  backBtn: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textPrimary,
  },
  scrollContent: {
    padding: SPACING.xl,
  },
  subtitle: {
    fontSize: 15,
    color: COLORS.textMuted,
    marginBottom: SPACING.xxl,
    textAlign: "center",
  },
  categoryCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.xl,
    marginBottom: 15,
    ...SHADOWS.md,
  },
  categoryHeader: {
    marginBottom: SPACING.md,
  },
  categoryTitle: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textPrimary,
    marginBottom: 6,
  },
  categoryDescription: {
    fontSize: FONT_SIZE.md,
    color: COLORS.textMuted,
    marginBottom: SPACING.sm,
  },
  categoryInfo: {
    fontSize: 13,
    color: COLORS.textDisabled,
    marginBottom: SPACING.xs,
  },
  startButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.xl,
    borderRadius: RADIUS.md,
    marginTop: 10,
    alignItems: "center",
  },
  startButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: SPACING.md,
    fontSize: 15,
    color: COLORS.textMuted,
  },
  quizHeader: {
    backgroundColor: COLORS.primary,
    padding: SPACING.xl,
    paddingTop: 60,
    ...SHADOWS.md,
  },
  quizTitle: {
    color: COLORS.white,
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    marginBottom: SPACING.sm,
    textAlign: "center",
  },
  progressText: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 15,
    textAlign: "center",
    marginTop: SPACING.xs,
  },
  answeredText: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: FONT_SIZE.md,
    textAlign: "center",
    marginTop: SPACING.xs,
  },
  quizContent: {
    flex: 1,
    padding: SPACING.xl,
  },
  questionText: {
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.xl,
    lineHeight: 26,
  },
  answerButton: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    ...SHADOWS.sm,
  },
  answerButtonSelected: {
    borderColor: COLORS.primary,
    backgroundColor: "#eff6ff",
  },
  answerText: {
    fontSize: 15,
    color: COLORS.textPrimary,
    lineHeight: 22,
  },
  answerTextSelected: {
    color: COLORS.primary,
    fontWeight: FONT_WEIGHT.semibold,
  },
  navigationContainer: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    padding: 15,
  },
  questionDots: {
    marginBottom: 15,
  },
  questionDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.borderLight,
    justifyContent: "center",
    alignItems: "center",
    marginRight: SPACING.sm,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  questionDotAnswered: {
    backgroundColor: "#eff6ff",
    borderColor: COLORS.primary,
  },
  questionDotCurrent: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  questionDotText: {
    fontSize: 13,
    color: COLORS.textMuted,
    fontWeight: FONT_WEIGHT.semibold,
  },
  questionDotTextActive: {
    color: COLORS.white,
    fontWeight: FONT_WEIGHT.bold,
  },
  navigationButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  navButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  navButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
  },
  finishButton: {
    flex: 1,
    backgroundColor: COLORS.success,
    paddingVertical: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  finishButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
  },
  resultsScroll: {
    flex: 1,
  },
  resultsScrollContent: {
    padding: SPACING.xl,
    paddingTop: 60,
    paddingBottom: SPACING.xl,
  },
  resultHeader: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 30,
    alignItems: "center",
    marginBottom: SPACING.xl,
    ...SHADOWS.md,
  },
  resultEmoji: {
    fontSize: 48,
    marginBottom: SPACING.md,
  },
  resultTitle: {
    fontSize: FONT_SIZE.title,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
  },
  resultScore: {
    fontSize: 36,
    fontWeight: FONT_WEIGHT.bold,
    color: COLORS.primary,
    marginBottom: 6,
  },
  resultPercentage: {
    fontSize: FONT_SIZE.xl,
    color: COLORS.textMuted,
    fontWeight: FONT_WEIGHT.semibold,
  },
  resultsSummary: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.xl,
    marginBottom: SPACING.xl,
    ...SHADOWS.md,
  },
  summaryTitle: {
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.bold,
    marginBottom: 15,
    color: COLORS.textPrimary,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  summaryLabel: {
    fontSize: 15,
    color: COLORS.textMuted,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textPrimary,
  },
  correctValue: {
    color: COLORS.success,
  },
  wrongValue: {
    color: COLORS.error,
  },
  questionsReviewTitle: {
    fontSize: FONT_SIZE.xxl,
    fontWeight: FONT_WEIGHT.bold,
    marginBottom: 15,
    color: COLORS.textPrimary,
  },
  reviewCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: 15,
    ...SHADOWS.md,
    borderLeftWidth: 4,
    borderLeftColor: "#e5e7eb",
  },
  reviewCardCorrect: {
    borderLeftColor: COLORS.success,
  },
  reviewCardWrong: {
    borderLeftColor: COLORS.error,
  },
  reviewCardUnanswered: {
    borderLeftColor: COLORS.warning,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: SPACING.md,
    alignItems: "center",
  },
  reviewNumber: {
    fontSize: 13,
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textMuted,
  },
  reviewStatus: {
    fontSize: 13,
    fontWeight: FONT_WEIGHT.semibold,
  },
  reviewStatusCorrect: {
    color: COLORS.success,
  },
  reviewStatusWrong: {
    color: COLORS.error,
  },
  reviewStatusUnanswered: {
    color: COLORS.warning,
  },
  reviewQuestion: {
    fontSize: FONT_SIZE.lg,
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
    lineHeight: 24,
  },
  reviewAnswer: {
    padding: SPACING.md,
    backgroundColor: "#f9fafb",
    borderRadius: RADIUS.md,
    marginBottom: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  reviewAnswerCorrect: {
    backgroundColor: "#ecfdf5",
    borderColor: COLORS.success,
  },
  reviewAnswerWrong: {
    backgroundColor: "#fef2f2",
    borderColor: COLORS.error,
  },
  reviewAnswerText: {
    fontSize: FONT_SIZE.md,
    color: COLORS.textPrimary,
    flex: 1,
    lineHeight: 20,
  },
  reviewAnswerTextBold: {
    fontWeight: FONT_WEIGHT.semibold,
    color: COLORS.textPrimary,
  },
  reviewAnswerMark: {
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.bold,
    marginLeft: 10,
    color: COLORS.success,
  },
  reviewAnswerMarkWrong: {
    fontSize: FONT_SIZE.xl,
    fontWeight: FONT_WEIGHT.bold,
    marginLeft: 10,
    color: COLORS.error,
  },
  resultsActions: {
    padding: SPACING.xl,
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    gap: 10,
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  retryButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
  },
  backButton: {
    backgroundColor: COLORS.textMuted,
    paddingVertical: 14,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  backButtonText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: FONT_WEIGHT.semibold,
  },
});
